package com.example.ishop.validators;

import com.example.ishop.dto.ProductDTO;
import com.example.ishop.exceptions.DemoException;
import org.springframework.stereotype.Component;

@Component
public class RequestValidator {
    public void validateAddProduct(final ProductDTO productDTO) throws DemoException {
        if (productDTO.getId() != null) {
            throw new DemoException("Product ID could not be set manually. It is autogenerated");
        }
        if (productDTO.getName().length() < 1 || productDTO.getName().length() > 255) {
            throw new DemoException("Product NAME length should be > 0 and less than 256");
        }
        if (productDTO.getPrice() == null || productDTO.getPrice().length() < 1) {
            throw new DemoException("Product PRICE is mandatory");
        } else {
            try {
                Double.parseDouble(productDTO.getPrice());
            } catch (NumberFormatException e) {
                throw new DemoException("Product PRICE should be numeric");
            }
        }
    }

    public void validateDeleteProduct(final ProductDTO productDTO) throws DemoException {
        if (productDTO.getId().length() != 24) {
            throw new DemoException("Product ID notValid");
        }
    }

    public void validateUpdateProduct(final ProductDTO productDTO) throws DemoException {
        if (productDTO.getId().length() != 24) {
            throw new DemoException("Product ID notValid");
        }
        if (productDTO.getName().length() > 0 && (productDTO.getName().length() < 1 || productDTO.getName().length() > 255)) {
            throw new DemoException("Product NAME length should be > 0 and less than 256");
        }
        if (productDTO.getPrice().length() > 0) {
            try {
                Double.parseDouble(productDTO.getPrice());
            } catch (NumberFormatException e) {
                throw new DemoException("Product PRICE should be numeric");
            }
        }
    }

    public void validateSearchProduct(ProductDTO productDTO) throws DemoException {
        if (productDTO.getId().length() > 0 && productDTO.getId().length() != 24) {
            throw new DemoException("Product ID notValid");
        }
        if (productDTO.getName().length() > 0 && productDTO.getName().length() > 255) {
            throw new DemoException("Product NAME length should be > 0 and less than 256");
        }
    }
}
